### PR TITLE
Add amazon sponsor logo

### PR DESCRIPTION
**Pull request by JosephCarpenter**

### CODE REVIEW

**Comment by ArchdukeTim** [comment]
Hold off on this. I gotta make sure you used a proper logo

**Comment by JosephCarpenter** [comment]
Mr. Knight sent me the logo so it should be ok?

**Comment by AndrewLester** [comment]
Any status updates on this one or should we merge it? Since Mr. Knight sent the logo my guess is it's good, but it can't hurt to double check.

**Comment by ArchdukeTim** [comment]
Oh I forgot about this. You should be good to go

**Review by AndrewLester — APPROVED** [review]
Sounds good.

**Pull request merged**
