### PR TITLE
Mention DLC inclusion in team images README

### PR DESCRIPTION
**Pull request by ErikBoesen**
I just remembered this and thought it might be neat to include here so future members can remember :)

### CODE REVIEW

**Comment by JosephCarpenter** [comment]
I don't seem to see the team portraits anywhere in the DLC you linked—do you know where they are?

**Comment by ErikBoesen** [comment]
Our portraits weren't in there, but there was a guide for how to draw portraits that look like ours which cited us as the origin of the technique. Maybe it was a different DLC pack that year? I didn't actually look in the one I linked.

**Comment by JosephCarpenter** [comment]
Yeah this one was just a folder generic deep-space posters and a few sound effects, I didn't see anything about portraits or portrait guides. Maybe it was in DLC Pack 1 or something?

**Comment by ErikBoesen** [comment]
Found a new link in the Wayback Machine that definitely works.

**Comment by AndrewLester** [comment]
Yo they actually mention your and Tim.

**Comment by ErikBoesen** [comment]
Just gonna merge this myself. In the future you guys can feel free to merge if I make any more PRs

**Pull request merged**
