### PR TITLE
add eve

### PR DESCRIPTION
**Pull request by MyaTaheri**

### CODE REVIEW

**Review by ErikBoesen — APPROVED** [review]

**Comment by BenBerol** [comment]
Eve is a senior so her graduation year is '24

**Comment by MyaTaheri** [comment]
Ok! I edited her graduation year

**Review by ErikBoesen — APPROVED** [review]
Still says she's a first year?

**Comment by MyaTaheri** [comment]
Yup, first year means first year on the team and she joined this year as a senior

**Pull request merged**
