### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by Git-HorizonZz**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Is there anyone else on the team who's willing to review these PRs? Generally we should have at least one other member give a review before merging.

**Comment by Git-HorizonZz** [comment]
I usually have people review the PRs in real life before merging. It
definitely would be bad if I just pushed everything without reviews 😅

**Comment by ErikBoesen** [comment]
Gotcha, it would be best to do that through Github so it's most visible!

**Comment by Git-HorizonZz** [comment]
True, true. I’ll keep that in mind for the future ones.David O’ReganOn Dec 6, 2022, at 4:30 PM, Erik Kieran Boesen ***@***.***> wrote:﻿
Gotcha, it would be best to do that through Github so it's most visible!

**Pull request merged**
