### PR TITLE
Add new profile photos

### PR DESCRIPTION
**Pull request by ErikBoesen**
These are all just direct copies of portraits we drew for people who are no longer on the team, or slight modifications of the same. Use what we have, right?

### CODE REVIEW

**Comment by ErikBoesen** [comment]
@AdamSchults See if you can figure out how to approve this pull request!

**Comment by ErikBoesen** [comment]
Oh, Ian, you should have merging access to this repo. Let me make sure you have that

**Comment by ianzullo** [comment]
image

**Comment by ErikBoesen** [comment]
Yeah somehow I hadn't added you to the website team yet. You should have merge access now. But for this PR just wait until Adam has a chance to practice reviewing.

**Comment by ErikBoesen** [comment]
Can you approve? @twinters007

**Pull request merged**
