### PR TITLE
Fix Nav Button

### LINKED ISSUE #57: Member portraits interpolate weirdly on mobile Chrome
Example:

http://imgur.com/a/rSzjQ

### PR DESCRIPTION
**Pull request by va6996**
Fixes #57

### CODE REVIEW

**Comment by ErikBoesen** [comment]
First: This has nothing at all to do with #57.
Second: This is not user-friendly imo. Some of the pages on this site are very, very long and we don't want to force users to scroll back to the top of the page every time they need to open the menu. I agree that there is some cosmetic advantage to not having the three white bars on top of everything, but I would personally advocate for giving those bars a background instead. Feel free to do that and I'll consider merging.

**Comment by va6996** [comment]
Oh sorry, I didn't correctly understand the issue. I infered that the assets very overlapping

**Comment by ErikBoesen** [comment]
Oh, no problem.

**Comment by va6996** [comment]
In that case, you can consider to make the nav-bar look like its supposed to be there, instead of just having 3 lines coming over everything like used in Page Top buttons.

**Comment by ErikBoesen** [comment]
In #61 I made the button continue to float, but have a grey background so it's clear that it's intentional.

**Pull request closed without merging**
