### PR TITLE
2018

### PR DESCRIPTION
**Pull request by NathanielHorne**

### CODE REVIEW

**Comment by NathanielHorne** [comment]
Okay full changes to the 2018 file. Please merge.

**Comment by ErikBoesen** [comment]
@NathanielHorne this branch has already been merged. You will need to pull from upstream and do the new commits again. Ask Joe for help, he's done this a bunch of times.

**Comment by NathanielHorne** [comment]
Done Erik. The changes have been made. I'll update the pull request.

**Comment by NathanielHorne** [comment]
The changes were made in a past pull request. The changes have already been made.

**Comment by ErikBoesen** [comment]
The problem is that this PR contains duplicates of commits I've already merged.

**Comment by ErikBoesen** [comment]
Also, just so you know, closing and reopening your PR doesn't do anything. If you just closed and commented by accident, that's understandable; just wanted to make sure you knew that doesn't update your PR in any way.

**Comment by NathanielHorne** [comment]
Darn, there are conflicting files. I'll fix that.

**Comment by NathanielHorne** [comment]
Okay. This needs to be done NOW please.

**Pull request closed without merging**
