### PR TITLE
Footer

### LINKED ISSUE #183: New sponsors for footer
All these need to be re-added. Some have logos which can be found if you go back a few months in the commit history.

### PR DESCRIPTION
**Pull request by NathanielHorne**
Fixes #183.

### CODE REVIEW

**Comment by ErikBoesen** [comment]
This duplicates all your commits from #184. Were you trying to do that?

**Comment by NathanielHorne** [comment]
Nope.

**Comment by NathanielHorne** [comment]
I rebased the branch that dealt with editing the team page to master, made these changes there, and switched to a different branch for this PR.

**Comment by ErikBoesen** [comment]
They may have started from a common root. If the branch was created while working on another branch it would have been based off that one.

**Pull request closed without merging**
