### PR TITLE
Add basic layout for simpler pages and make countdown dates correct

### PR DESCRIPTION
**Pull request by AndrewLester**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
Ah, off-by-one errors, the best.

Not sure why you have to merge `upstream/master` so much, but this looks good.

**Comment by AndrewLester** [comment]
I think I had to merge upstream master because I accidentally merged instead of rebased.

**Comment by AndrewLester** [comment]
Yeah uh, months start at 0 days of the month start at 1...

**Comment by ErikBoesen** [comment]
Date classes are a nightmare in every language.

#interplanetaryrecognitionofunixtimewhen

**Pull request merged**
