### PR TITLE
Use pre-blurred and darkened image and video

### PR DESCRIPTION
**Pull request by calebeby**
This makes scrolling a whole lot smoother.

The command to blur the video is this:

```bash
$ ffmpeg -i video.mp4 -vf boxblur=2,eq=0.9:-0.15 video-blur.mp4
```

For the backup image it is the same, but with the different paths.

### CODE REVIEW

**Comment by ErikBoesen** [comment]
I had no idea there was a command for this. Thank you so much, I've been trying to find a solution to this this evening. I'll give it a look right now.

**Comment by ErikBoesen** [comment]
Can you make it a bit darker and a bit less blurry? Try to get it as close as possible to the current site; I like how that looks a lot.

Also, why is there a png and a jpg for the fallback background?

**Comment by calebeby** [comment]
Ok. Will update.

First I make a PNG for it, and then decided JPG was more suitable and forgot to delete PNG.

**Comment by ErikBoesen** [comment]
Okay. Would JPG really be more suitable? It's a very scaled-down, discolored, and blurred version of a somewhat grainy frame from a GoPro video. Don't you think the benefits of JPG in this situation would be negative?

**Comment by calebeby** [comment]
Aren't JPG's better for real-life images and PNG's better for flat images?

http://www.labnol.org/software/tutorials/jpeg-vs-png-image-quality-or-bandwidth/5385/

**Comment by ErikBoesen** [comment]
Yeah, but this is barely a real-life photo anymore.

**Comment by calebeby** [comment]
The PNG is 72K and the JPG is 12K.

**Comment by ErikBoesen** [comment]
Okay, fair.

**Comment by ErikBoesen** [comment]
Hmmm... still too much contrast and blur. I'll look into it tomorrow. Thanks for telling me about this!

**Comment by calebeby** [comment]
Here's the article I found about the filters:

https://wjwoodrow.wordpress.com/2013/11/22/adjusting-video-contrast-brightness-saturation-and-color-balance-with-ffmpeg/

Here is the update to that article:

https://wjwoodrow.wordpress.com/2015/07/12/more-ffmpeg-hell/

**Comment by calebeby** [comment]
Also: use `ffplay` to preview the video, without the output file.

**Pull request closed without merging**
