### PR TITLE
Add first batch of team members

### PR DESCRIPTION
**Pull request by ianzullo**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
I don't like how you replaced Keenan Hom's photo with one with way less detail...

**Comment by ianzullo** [comment]
If I'm being honest I prefer using less shading on the shirts and hair beyond shadows but I'm indifferent to which one actually makes it on the site.

**Comment by ErikBoesen** [comment]
Also, a lot of these people look really small and sort of... shriveled?

**Comment by ianzullo** [comment]
I get small because thats just how the pictures were sent to me but shriveled?

**Comment by ErikBoesen** [comment]
What I meant is that the heads look a bit small and undetailed.

**Comment by ianzullo** [comment]
They look fine to me.

**Comment by ErikBoesen** [comment]
Eh, whatever, I'll merge when you remove the replacement of Keenan's photo.

**Comment by ianzullo** [comment]
Done.

**Pull request merged**
