### PR TITLE
Add team members

### PR DESCRIPTION
**Pull request by BenGitsMagic**

### CODE REVIEW

**Comment by BenGitsMagic** [comment]
Currently missing pictures for: Smridhi, joe donovan, and nate

**Comment by ErikBoesen** [comment]
You could consider keeping Lorita's photo around to be used for a future member rather than removing the old file. Also, there are merge conflicts.

**Comment by ErikBoesen** [comment]
Try this to resolve your conflicts: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

**Comment by ErikBoesen** [comment]
You can also use the "Resolve conflicts" button on this PR.

**Review by Git-HorizonZz — APPROVED** [review]
all good

**Review by BobbyMi11er — APPROVED** [review]

**Pull request merged**
