### PR TITLE
Make favicon circular

### LINKED ISSUE #333: Make favicon circular
Put a background color around the fist in the icon image.

### PR DESCRIPTION
**Pull request by ianzullo**
Resolves #333

### CODE REVIEW

**Comment by ianzullo** [comment]
this is another one i made im not sure how good it looks tho
game
screen shot 2019-01-23 at 7 48 55 pm

**Comment by ErikBoesen** [comment]
@ianzullo It's easier to see, but it doesn't make much sense in a circular context. I've found that while the fist logo is generally nice, it's not very good at fitting into anything at a 1:1 ratio. I'd suggest just cropping the GitHub photo into a circle.

**Comment by ianzullo** [comment]
i mean it is centered but thats the problem with the fist logo. it doesnt rly center in circles well because of the wrench.

**Comment by ErikBoesen** [comment]
@ianzullo Yeah that's what I'm saying ^

**Comment by ianzullo** [comment]
favi
screen shot 2019-01-23 at 8 15 05 pm

thoughts

**Comment by ErikBoesen** [comment]
@ianzullo That looks great, give it a shot

**Pull request merged**
