### PR TITLE
added david (myself) to website + picture; fixed missing </div> ending tag

### PR DESCRIPTION
**Pull request by Git-HorizonZz**

### CODE REVIEW

**Comment by ErikBoesen** [comment]
I recommend cleaning up the semitransparent edges of your portrait such that only a few colors are used, rather than the gradient that is currently there. Otherwise looks great!

**Comment by Git-HorizonZz** [comment]
ok thanks

**Comment by BrandonWerbel** [comment]
You may also want to take out the floating black area in the top left corner.

**Comment by Git-HorizonZz** [comment]
didnt see that lol

**Comment by Git-HorizonZz** [comment]
done

**Review by BrandonWerbel — APPROVED** [review]

**Pull request merged**
