### PR TITLE
Categorize assets/img and place TJ steam night images correctly.

### LINKED ISSUE #193: assets/img needs categorization
When I was setting the website up I didn't do a great job of organizing our assets...

### LINKED ISSUE #258: TJ Steam Night Images are in Wrong Place
The 2017 STEAM night images are under the field help page on outreach. This is an easy fix.

### PR DESCRIPTION
**Pull request by NathanielHorne**
Fixes #258 
Fixes #193

### CODE REVIEW

**Comment by NathanielHorne** [comment]
I still need to update the addresses of every image to make sure all the images show up.

**Comment by ErikBoesen** [comment]
Hate to break it to you, but... you have some conflicts.

**Comment by NathanielHorne** [comment]
Yeah I accidentally deleted some images. I fixed it though and will update this pr soon.

**Comment by NathanielHorne** [comment]
@ErikBoesen What needs to be done?

**Comment by ErikBoesen** [comment]
See my comment above

**Comment by ErikBoesen** [comment]
Go back into previous commits to find the images. If not you can get them from Twitter.

**Comment by NathanielHorne** [comment]
@ErikBoesen All changes have been made boss. I tried squashing some commits and it just made things worse. It **should** all be one commit but it isn't. Would this still work?

**Comment by NathanielHorne** [comment]
No this is broken, I fixed it in another branch

**Pull request closed without merging**
